// Command breakeven recomputes the fee threshold that governs every strategy in
// the lobby, using the venue's live fee schedule and its own price history
// rather than an assumed rate.
//
// It answers one question per market: how long must a position be held before
// the expected price move covers the round trip? That number decides which
// mechanics are alive on a venue and which are mathematically dead — see
// docs/fee-model.md.
//
//	go run ./cmd/breakeven                 # markdown table to stdout
//	go run ./cmd/breakeven -hours 48       # more history
package main

import (
	"context"
	"flag"
	"fmt"
	"math"
	"os"
	"sort"
	"time"

	"github.com/wagmiCTO/super-agent/services/internal/fixed"
	"github.com/wagmiCTO/super-agent/services/internal/venue"
	"github.com/wagmiCTO/super-agent/services/internal/venue/perpl"
)

// builderScenarios are the builder-fee rates the product model considers, in
// basis points.
var builderScenarios = []int64{0, 2, 5, 10}

// hyperliquid is the schedule the engine has to port to. Rates are the public
// base tier; it charges on every fill, which is the difference that matters.
var hyperliquid = venue.FeeSchedule{
	MakerRate: fixed.MustParse("0.00015"),
	TakerRate: fixed.MustParse("0.00045"),
	ChargedOn: venue.FeeOnEveryFill,
}

// minutesPerYear is used to annualize a per-minute standard deviation.
const minutesPerYear = 365 * 24 * 60

type stats struct {
	market venue.Market
	// sigmaMinute is the standard deviation of one-minute log returns.
	sigmaMinute float64
	sigmaAnnual float64
	bars        int
}

func main() {
	hours := flag.Int("hours", 17, "hours of 1m history to sample (1024 bars max per request)")
	notional := flag.Float64("notional", 50, "position notional to price per-order fees against")
	flag.Parse()

	if err := run(context.Background(), *hours, *notional); err != nil {
		fmt.Fprintf(os.Stderr, "breakeven: %v\n", err)
		os.Exit(1)
	}
}

func run(ctx context.Context, hours int, notional float64) error {
	cfg, err := perpl.ConfigFromEnv()
	if err != nil {
		return err
	}
	adapter, err := perpl.New(ctx, cfg, nil)
	if err != nil {
		return err
	}
	defer adapter.Close()

	markets, err := adapter.Markets(ctx)
	if err != nil {
		return err
	}
	sort.Slice(markets, func(i, j int) bool { return markets[i].Symbol < markets[j].Symbol })

	to := time.Now()
	from := to.Add(-time.Duration(hours) * time.Hour)

	var all []stats
	for _, m := range markets {
		candles, err := adapter.Candles(ctx, m.Symbol, time.Minute, from, to)
		if err != nil {
			fmt.Fprintf(os.Stderr, "  %s: %v\n", m.Symbol, err)
			continue
		}
		s, ok := measure(m, candles)
		if !ok {
			fmt.Fprintf(os.Stderr, "  %s: not enough history (%d bars)\n", m.Symbol, len(candles))
			continue
		}
		all = append(all, s)
	}
	if len(all) == 0 {
		return fmt.Errorf("no market had usable history")
	}

	report(all, cfg.Network.Name, hours, to, fixed.MustParse(fmt.Sprintf("%.2f", notional)))
	return nil
}

// measure computes the per-minute volatility from close-to-close log returns.
func measure(m venue.Market, candles []venue.Candle) (stats, bool) {
	if len(candles) < 30 {
		return stats{}, false
	}
	var rets []float64
	for i := 1; i < len(candles); i++ {
		prev, cur := candles[i-1].C.Float64(), candles[i].C.Float64()
		if prev <= 0 || cur <= 0 {
			continue
		}
		rets = append(rets, math.Log(cur/prev))
	}
	if len(rets) < 30 {
		return stats{}, false
	}
	var mean float64
	for _, r := range rets {
		mean += r
	}
	mean /= float64(len(rets))

	var variance float64
	for _, r := range rets {
		variance += (r - mean) * (r - mean)
	}
	variance /= float64(len(rets) - 1)
	sigma := math.Sqrt(variance)

	return stats{
		market:      m,
		sigmaMinute: sigma,
		sigmaAnnual: sigma * math.Sqrt(minutesPerYear),
		bars:        len(candles),
	}, true
}

// expectedMove is the mean absolute move over t minutes for a driftless random
// walk: E|N(0, σ√t)| = σ√t·√(2/π), the 0.8·σ·√t of the concept note.
func expectedMove(sigmaMinute, minutes float64) float64 {
	return sigmaMinute * math.Sqrt(minutes) * math.Sqrt(2/math.Pi)
}

// minutesToBreakEven inverts expectedMove: how long until the expected move
// covers cost, as a fraction of notional.
func minutesToBreakEven(sigmaMinute, cost float64) float64 {
	if sigmaMinute <= 0 {
		return math.Inf(1)
	}
	x := cost / (sigmaMinute * math.Sqrt(2/math.Pi))
	return x * x
}

func report(all []stats, network string, hours int, at time.Time, notional fixed.D) {
	fmt.Printf("# Perpl break-even, measured\n\n")
	fmt.Printf("> Generated by `cmd/breakeven` on %s from %s, sampling %dh of 1m candles.\n",
		at.UTC().Format("2006-01-02 15:04 MST"), network, hours)
	fmt.Printf("> Fee rates are read from the venue's own market config, not assumed.\n\n")

	fmt.Printf("## Volatility and the cost of a round trip\n\n")
	fmt.Printf("| market | bars | σ annual | σ 1m | move 1m | move 5m | move 30m | round trip | break-even |\n")
	fmt.Printf("|---|---:|---:|---:|---:|---:|---:|---:|---:|\n")
	for _, s := range all {
		rt := s.market.Fees.RoundTripRate(false, false)
		cost := rt.Float64()
		fmt.Printf("| %s | %d | %.0f%% | %.3f bps | %.2f bps | %.2f bps | %.2f bps | %s bps | %s |\n",
			s.market.Symbol, s.bars,
			s.sigmaAnnual*100,
			s.sigmaMinute*10_000,
			expectedMove(s.sigmaMinute, 1)*10_000,
			expectedMove(s.sigmaMinute, 5)*10_000,
			expectedMove(s.sigmaMinute, 30)*10_000,
			rt.InBps(),
			formatMinutes(minutesToBreakEven(s.sigmaMinute, cost)))
	}

	fmt.Printf("\n## Break-even holding time by builder fee\n\n")
	fmt.Printf("Taker in, taker out. Perpl charges the round trip once; Hyperliquid charges it twice,\n")
	fmt.Printf("so the same builder rate costs twice as much there.\n\n")
	fmt.Printf("| market |")
	for _, bp := range builderScenarios {
		fmt.Printf(" perpl +%dbp |", bp)
	}
	for _, bp := range builderScenarios {
		fmt.Printf(" HL +%dbp |", bp)
	}
	fmt.Println()
	fmt.Printf("|---|")
	for range builderScenarios {
		fmt.Printf("---:|")
	}
	for range builderScenarios {
		fmt.Printf("---:|")
	}
	fmt.Println()

	for _, s := range all {
		fmt.Printf("| %s |", s.market.Symbol)
		for _, bp := range builderScenarios {
			sched := s.market.Fees
			sched.BuilderRate = fixed.Bps(bp)
			cost := sched.RoundTripRate(false, false).Float64()
			fmt.Printf(" %s |", formatMinutes(minutesToBreakEven(s.sigmaMinute, cost)))
		}
		for _, bp := range builderScenarios {
			sched := hyperliquid
			sched.BuilderRate = fixed.Bps(bp)
			cost := sched.RoundTripRate(false, false).Float64()
			fmt.Printf(" %s |", formatMinutes(minutesToBreakEven(s.sigmaMinute, cost)))
		}
		fmt.Println()
	}

	fmt.Printf("\n## Maker entry, priced against a %s notional\n\n", notional)
	fmt.Printf("A resting entry is charged at the maker rate, and on Perpl the exit is free either way,\n")
	fmt.Printf("so a maker entry looks nearly free — until the per-order posting fee is priced in.\n")
	fmt.Printf("That fee is a flat amount, so it hurts small positions most: it is what decides whether\n")
	fmt.Printf("a limit-order mechanic is viable at the stake our players actually use.\n\n")
	fmt.Printf("| market | taker in | maker in | posting fee | posting fee on %s | effective maker in | break-even |\n", notional)
	fmt.Printf("|---|---:|---:|---:|---:|---:|---:|\n")
	for _, s := range all {
		f := s.market.Fees
		makerRT := f.RoundTripRate(true, false)
		postRate := f.PostingFee.Div(notional)
		effective := makerRT.Add(postRate)
		fmt.Printf("| %s | %s bps | %s bps | %s | %s bps | %s bps | %s |\n",
			s.market.Symbol,
			f.RoundTripRate(false, false).InBps(),
			makerRT.InBps(),
			f.PostingFee,
			postRate.InBps(),
			effective.InBps(),
			formatMinutes(minutesToBreakEven(s.sigmaMinute, effective.Float64())))
	}

	fmt.Printf("\n## Leverage\n\n")
	fmt.Printf("Leverage multiplies notional and PnL alike, so it does not move any number above.\n")
	fmt.Printf("It does cap how small a stake can carry a given notional, and Perpl's caps are low.\n\n")
	fmt.Printf("| market | max leverage | liquidation leverage |\n")
	fmt.Printf("|---|---:|---:|\n")
	for _, s := range all {
		fmt.Printf("| %s | %sx | %sx |\n", s.market.Symbol, s.market.MaxLeverage, s.market.LiquidationLeverage)
	}

	fmt.Printf("\n## Caveats\n\n")
	fmt.Printf("- Volatility is measured on **%s**. Its price feed tracks the real market, but its\n", network)
	fmt.Printf("  order book does not: spread and depth are thinner than mainnet, so a market order\n")
	fmt.Printf("  pays slippage these numbers do not include. Slippage is a second cost on top of the\n")
	fmt.Printf("  fee and it hits the same short horizons hardest.\n")
	fmt.Printf("- The break-even column is the horizon at which the *expected* move covers the fee.\n")
	fmt.Printf("  It is a coin flip at that point, not a profit: half the outcomes are still losses.\n")
	fmt.Printf("  A mechanic needs a comfortable multiple of it, not equality.\n")
	fmt.Printf("- The posting fee is a per-order charge on the testnet deployment; mainnet reports it\n")
	fmt.Printf("  as zero on every market. Do not design a limit-order mechanic around the testnet value.\n")
	fmt.Printf("- Funding is excluded. It is a holding cost, so it works against long horizons exactly\n")
	fmt.Printf("  where the fee argument favours them.\n")
}

func formatMinutes(m float64) string {
	switch {
	case math.IsInf(m, 1) || m > 60*24*30:
		return "never"
	case m < 1:
		return fmt.Sprintf("%.0fs", m*60)
	case m < 90:
		return fmt.Sprintf("%.0fm", m)
	case m < 60*48:
		return fmt.Sprintf("%.1fh", m/60)
	default:
		return fmt.Sprintf("%.1fd", m/(60*24))
	}
}
