/**
 * GENERATED by `node design/style/export-theme.mjs` — do not edit.
 *
 * The values come from the token blocks in
 * `design/path/tradeagent-proto.html`, which is where a theme is designed.
 * Change them there and re-run, or the app and the prototype drift apart.
 *
 * Two rules the token names encode, worth keeping in mind when using them:
 *
 *  - `fill`/`onFill` is the strong filled surface (primary button, banner);
 *    `accent`/`onAccent` is the brand mark. They are the same colour in one
 *    skin and different in the other, so never substitute one for the other.
 *  - `up`/`down` are market direction and `riskCalm`/`riskWarm`/`riskHot`
 *    are how much can still go wrong. A hot day happens on winning positions
 *    too, so these never share a token.
 */

/** Every family the two skins need; load them all before rendering. */
export const FONT_FACES = {
  Archivo_400Regular: require('@expo-google-fonts/archivo/400Regular/Archivo_400Regular.ttf'),
  Archivo_500Medium: require('@expo-google-fonts/archivo/500Medium/Archivo_500Medium.ttf'),
  Archivo_600SemiBold: require('@expo-google-fonts/archivo/600SemiBold/Archivo_600SemiBold.ttf'),
  Archivo_700Bold: require('@expo-google-fonts/archivo/700Bold/Archivo_700Bold.ttf'),
  JetBrainsMono_400Regular: require('@expo-google-fonts/jetbrains-mono/400Regular/JetBrainsMono_400Regular.ttf'),
  JetBrainsMono_600SemiBold: require('@expo-google-fonts/jetbrains-mono/600SemiBold/JetBrainsMono_600SemiBold.ttf'),
  JetBrainsMono_700Bold: require('@expo-google-fonts/jetbrains-mono/700Bold/JetBrainsMono_700Bold.ttf'),
  SpaceGrotesk_400Regular: require('@expo-google-fonts/space-grotesk/400Regular/SpaceGrotesk_400Regular.ttf'),
  SpaceGrotesk_500Medium: require('@expo-google-fonts/space-grotesk/500Medium/SpaceGrotesk_500Medium.ttf'),
  SpaceGrotesk_600SemiBold: require('@expo-google-fonts/space-grotesk/600SemiBold/SpaceGrotesk_600SemiBold.ttf'),
  SpaceGrotesk_700Bold: require('@expo-google-fonts/space-grotesk/700Bold/SpaceGrotesk_700Bold.ttf'),
  SpaceMono_400Regular: require('@expo-google-fonts/space-mono/400Regular/SpaceMono_400Regular.ttf'),
  SpaceMono_700Bold: require('@expo-google-fonts/space-mono/700Bold/SpaceMono_700Bold.ttf'),
} as const;

export type ThemeName = 'paper' | 'terminal';

export type ThemeColor = 'ground' | 'paper' | 'raised' | 'soft' | 'line' | 'hair' | 'ink' | 'body' | 'text2' | 'muted' | 'dim' | 'onInk' | 'accent' | 'onAccent' | 'fill' | 'onFill' | 'up' | 'onUp' | 'down' | 'onDown' | 'danger' | 'onDanger' | 'dangerSoft' | 'scrim' | 'glass' | 'glow' | 'chip' | 'onChip' | 'shadowPhone' | 'shadowMenu' | 'ring' | 'ring0' | 'chartLine' | 'chartLine2' | 'chartGrid' | 'chartAxis' | 'chartUp' | 'chartDown' | 'chartZone' | 'chartBand' | 'btnLine' | 'cardBg' | 'cardLine' | 'onAccentDim' | 'riskCalm' | 'riskWarm' | 'riskHot';
type RadiusKey = 'rXs' | 'rSm' | 'rMd' | 'rLg' | 'rXl';
type SpaceKey = 's1' | 's2' | 's3' | 's4' | 's5' | 's6';
type TypeKey = 't2xs' | 'tXs' | 'tSm' | 'tMd' | 'tLg' | 'tXl' | 't2xl' | 't3xl' | 'tHero' | 'tMega';
type SizeKey = 'btnH' | 'udH' | 'bw';
export type Weight = 400 | 500 | 600 | 700;

/**
 * Declared rather than inferred: with `as const` each skin gets its own
 * literal types, and indexing the union of the two collapses to `never`.
 */
export type Theme = {
  color: Record<ThemeColor, string>;
  radius: Record<RadiusKey, number>;
  space: Record<SpaceKey, number>;
  type: Record<TypeKey, number>;
  size: Record<SizeKey, number>;
  heading: { weight: number; tracking: number };
  tracking: number;
  elevated: boolean;
  faces: { display: Record<Weight, string>; num: Record<Weight, string> };
};

export const Themes: Record<ThemeName, Theme> = {
  paper: {
    "color": {
      "ground": "#EFEDE9",
      "paper": "#FFFFFF",
      "raised": "#FBFAF9",
      "soft": "#F3F1EE",
      "line": "#DAD5CE",
      "hair": "#E8E4DE",
      "ink": "#0E100F",
      "body": "#3A3733",
      "text2": "#514C46",
      "muted": "#6E6862",
      "dim": "#97918A",
      "onInk": "#FBFAF9",
      "accent": "#836EF9",
      "onAccent": "#FFFFFF",
      "fill": "#836EF9",
      "onFill": "#FFFFFF",
      "up": "#1C9A6B",
      "onUp": "#FFFFFF",
      "down": "#DC5546",
      "onDown": "#FFFFFF",
      "danger": "#DC5546",
      "onDanger": "#FFFFFF",
      "dangerSoft": "#FBE7E4",
      "scrim": "rgba(14,16,15,0.38)",
      "glass": "rgba(255,255,255,0.90)",
      "glow": "rgba(131,110,249,0.28)",
      "chip": "rgba(14,16,15,0.82)",
      "onChip": "#FFFFFF",
      "shadowPhone": "rgba(14,16,15,0.16)",
      "shadowMenu": "rgba(14,16,15,0.14)",
      "ring": "rgba(131,110,249,0.35)",
      "ring0": "rgba(131,110,249,0)",
      "chartLine": "#0E100F",
      "chartLine2": "#97918A",
      "chartGrid": "#E8E4DE",
      "chartAxis": "#DAD5CE",
      "chartUp": "#1C9A6B",
      "chartDown": "#DC5546",
      "chartZone": "rgba(131,110,249,0.08)",
      "chartBand": "#F3F1EE",
      "btnLine": "#DAD5CE",
      "cardBg": "#FFFFFF",
      "cardLine": "transparent",
      "onAccentDim": "#CFC4FC",
      "riskCalm": "#1C9A6B",
      "riskWarm": "#C8890A",
      "riskHot": "#DC5546"
    },
    "radius": {
      "rXs": 4,
      "rSm": 8,
      "rMd": 12,
      "rLg": 16,
      "rXl": 22
    },
    "space": {
      "s1": 5,
      "s2": 10,
      "s3": 14,
      "s4": 18,
      "s5": 22,
      "s6": 28
    },
    "type": {
      "t2xs": 11,
      "tXs": 12,
      "tSm": 14,
      "tMd": 16,
      "tLg": 18,
      "tXl": 22,
      "t2xl": 29,
      "t3xl": 34,
      "tHero": 46,
      "tMega": 60
    },
    "size": {
      "btnH": 56,
      "udH": 82,
      "bw": 1
    },
    "heading": {
      "weight": 700,
      "tracking": -0.025
    },
    "tracking": 0.05,
    "elevated": true,
    "faces": {
      "display": {
        "400": "SpaceGrotesk_400Regular",
        "500": "SpaceGrotesk_500Medium",
        "600": "SpaceGrotesk_600SemiBold",
        "700": "SpaceGrotesk_700Bold"
      },
      "num": {
        "400": "SpaceMono_400Regular",
        "500": "SpaceMono_400Regular",
        "600": "SpaceMono_700Bold",
        "700": "SpaceMono_700Bold"
      }
    }
  },
  terminal: {
    "color": {
      "ground": "#060F0D",
      "paper": "#0C1917",
      "raised": "#112421",
      "soft": "#142925",
      "line": "#23453E",
      "hair": "#1A3831",
      "ink": "#E4F3F0",
      "body": "#C2DBD6",
      "text2": "#A6C6C0",
      "muted": "#7CA29B",
      "dim": "#5C807A",
      "onInk": "#05201C",
      "accent": "#50D2C1",
      "onAccent": "#05201C",
      "fill": "#50D2C1",
      "onFill": "#05201C",
      "up": "#50D2C1",
      "onUp": "#05201C",
      "down": "#F0728A",
      "onDown": "#2A0810",
      "danger": "#F0728A",
      "onDanger": "#2A0810",
      "dangerSoft": "#3A1520",
      "scrim": "rgba(3,10,9,0.62)",
      "glass": "rgba(12,25,23,0.88)",
      "glow": "rgba(80,210,193,0.30)",
      "chip": "rgba(6,15,13,0.88)",
      "onChip": "#E4F3F0",
      "shadowPhone": "rgba(0,0,0,0.55)",
      "shadowMenu": "rgba(0,0,0,0.45)",
      "ring": "rgba(80,210,193,0.38)",
      "ring0": "rgba(80,210,193,0)",
      "chartLine": "#50D2C1",
      "chartLine2": "#7FA29B",
      "chartGrid": "#17332D",
      "chartAxis": "#23453E",
      "chartUp": "#50D2C1",
      "chartDown": "#F0728A",
      "chartZone": "rgba(80,210,193,0.09)",
      "chartBand": "#112421",
      "btnLine": "#23453E",
      "cardBg": "#142925",
      "cardLine": "#1A3831",
      "onAccentDim": "#2E6F65",
      "riskCalm": "#50D2C1",
      "riskWarm": "#E8B84B",
      "riskHot": "#F0728A"
    },
    "radius": {
      "rXs": 2,
      "rSm": 4,
      "rMd": 6,
      "rLg": 8,
      "rXl": 10
    },
    "space": {
      "s1": 3,
      "s2": 6,
      "s3": 9,
      "s4": 12,
      "s5": 16,
      "s6": 20
    },
    "type": {
      "t2xs": 10,
      "tXs": 11,
      "tSm": 13,
      "tMd": 14,
      "tLg": 16,
      "tXl": 19,
      "t2xl": 24,
      "t3xl": 29,
      "tHero": 40,
      "tMega": 50
    },
    "size": {
      "btnH": 48,
      "udH": 68,
      "bw": 1
    },
    "heading": {
      "weight": 600,
      "tracking": -0.005
    },
    "tracking": 0.07,
    "elevated": false,
    "faces": {
      "display": {
        "400": "Archivo_400Regular",
        "500": "Archivo_500Medium",
        "600": "Archivo_600SemiBold",
        "700": "Archivo_700Bold"
      },
      "num": {
        "400": "JetBrainsMono_400Regular",
        "500": "JetBrainsMono_400Regular",
        "600": "JetBrainsMono_600SemiBold",
        "700": "JetBrainsMono_700Bold"
      }
    }
  },
};

/** Paper ships first; Terminal exists so hardcoded values fail loudly. */
export const DEFAULT_THEME: ThemeName = 'paper';

/**
 * React Native picks a face by family name, not by `fontWeight`: on Android a
 * weight on a custom family is ignored. Always go through this.
 */
export function face(theme: Theme, kind: 'display' | 'num', weight: Weight = 400): string {
  return theme.faces[kind][weight];
}
