// Embeds TradingView's Lightweight Charts standalone build as a string, so
// the native chart WebView carries the library with the app instead of
// fetching it. Generated file; run via `npm run gen:chart` (also postinstall).
import { readFile, writeFile } from 'node:fs/promises';

const src = await readFile(new URL('../node_modules/lightweight-charts/dist/lightweight-charts.standalone.production.js', import.meta.url), 'utf8');
const out = `// Generated by scripts/embed-chart.mjs — do not edit.\n// Lightweight Charts ${JSON.parse(await readFile(new URL('../node_modules/lightweight-charts/package.json', import.meta.url), 'utf8')).version}, Apache-2.0, © TradingView.\nconst vendor: string = ${JSON.stringify(src)};\nexport default vendor;\n`;
await writeFile(new URL('../src/chart/vendor.generated.ts', import.meta.url), out);
console.log(`embedded lightweight-charts (${(src.length / 1024).toFixed(0)} KB)`);
