/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            status?: "ok";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/markets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tradable markets with the fee schedule that applies to this account */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Market"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Account balance, open positions, limits in force and how much of them is used
         * @description Per-wallet requests carry `X-Account-Address` and `X-Strategy`: the
         *     strategy picks the wallet's key for it and the limits that key trades
         *     under (one key per strategy, derived from the passkey). A wallet that
         *     registered a request-signing key (POST /v1/auth/keys) must also sign
         *     every request: `X-Auth-Key` (Ed25519 public key, hex), `X-Auth-Time`
         *     (unix seconds) and `X-Auth-Signature` (hex) over
         *     `METHOD\nPATH?QUERY\nTIME\nSHA256(body)`, newline-separated.
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Which strategy's key and limits the request is for. */
                    "X-Strategy"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["State"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open a position
         * @description Sized by notional in collateral units; the service derives the size
         *     from the venue's mark price. Returns once the venue accepted or refused
         *     the order — fills may still be in flight for a resting order, but a
         *     market order is filled on return.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OpenRequest"];
                };
            };
            responses: {
                /** @description Accepted by the venue. Check `status`: a venue-side failure arrives here with status `failed` and a `rejection`. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Order"];
                    };
                };
                400: components["responses"]["Invalid"];
                403: components["responses"]["Denied"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["VenueRejected"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close the open position in a market
         * @description The service sizes the close from the venue's own position, never from
         *     the caller. Closing is never refused by the policy engine.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CloseRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Order"];
                    };
                };
                400: components["responses"]["Invalid"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["VenueRejected"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exchange/enroll/payload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start enrolling an exchange API key for a wallet
         * @description The platform generates an Ed25519 key pair and asks the venue for two
         *     things: the wallet's sign-in message, and the EIP-712 document that
         *     binds the new key to the wallet and to our builder terms. The wallet
         *     signs both — `sign_in_message` as a personal message (EIP-191),
         *     `typed_data` as EIP-712. `statement` is the prose the user reads. The
         *     private key waits on the server until `expires_at`.
         *
         *     The sign-in is what creates the wallet's profile at the venue on first
         *     contact; without it the venue refuses to enroll a key.
         *
         *     When signing with viem, pass `domain.chainId` as a **bigint**: given a
         *     string, viem drops chainId from the domain type and the venue rejects
         *     the signature.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description The wallet the key is for */
                        address: string;
                        /** @description Shown on the venue's key page. */
                        label?: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnrollPayload"];
                    };
                };
                400: components["responses"]["Invalid"];
                422: components["responses"]["VenueRejected"];
                /** @description No builder code configured; enrollment is unavailable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exchange/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finish enrolling with the wallet's signature
         * @description The platform signs the wallet in at the venue with `sign_in_signature`
         *     (creating its profile on first contact), then computes the EIP-712
         *     digest, signs it with the pending Ed25519 key as proof of possession,
         *     and submits it with `signature`. On success the key is stored and the
         *     platform can trade for this wallet. A handle is single-use.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        handle: string;
                        /** @description The wallet's EIP-191 signature over sign_in_message */
                        sign_in_signature: string;
                        /** @description The wallet's EIP-712 signature over typed_data */
                        signature: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnrolledKey"];
                    };
                };
                400: components["responses"]["Invalid"];
                422: components["responses"]["VenueRejected"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exchange/key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The enrolled key for a wallet and strategy, without secrets */
        get: {
            parameters: {
                query: {
                    address: string;
                    /** @description The strategy's key; empty for the wallet-wide key. */
                    strategy?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnrolledKey"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exchange/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every key enrolled for a wallet — which strategies are enabled */
        get: {
            parameters: {
                query: {
                    address: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnrolledKey"][];
                    };
                };
                400: components["responses"]["Invalid"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a request-signing key for a wallet
         * @description The device derives an Ed25519 key from the passkey and the wallet
         *     signs, as a personal message, the text
         *     `TradeAgent request-signing key\nWallet: <address, lowercase>\nKey: <public key hex>\nIssued: <RFC 3339, seconds>`.
         *     From then on every request for this wallet must be signed by a
         *     registered key (see GET /v1/state).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        address: string;
                        /** @description Ed25519 public key */
                        public_key: string;
                        /**
                         * Format: date-time
                         * @description Seconds precision; at most ten minutes old.
                         */
                        issued_at: string;
                        /** @description The wallet's EIP-191 signature */
                        signature: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            address: string;
                            public_key: string;
                        };
                    };
                };
                400: components["responses"]["Invalid"];
                /** @description The signature was not made by this wallet. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exchange/network": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Where a wallet opens its exchange account on-chain
         * @description An enrolled key only authorizes API access. To trade, the wallet itself must create an exchange account with collateral and allow order forwarding: approve(exchange_address, amount) on collateral_token, then createAccount(amount) and allowOrderForwarding(true) on exchange_address, with amount ≥ min_account_open_raw. The platform never holds a key that could send these.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExchangeNetwork"];
                    };
                };
                /** @description No builder code configured; enrollment is unavailable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/signals/ma-cross": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The MA Cross signal for a market
         * @description The strategy's signal, shared by everyone: closed one-minute bars with the fast and slow averages, which average is on top, and — for a few minutes after a cross — an open window inviting an entry in the cross's direction. The signal never places orders; the user does.
         */
        get: {
            parameters: {
                query: {
                    symbol: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MACrossSignal"];
                    };
                };
                404: components["responses"]["NotFound"];
                /** @description No signals are running. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/signals/rsi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The RSI signal for a market
         * @description Wilder's RSI over closed one-minute bars with the oversold and overbought zones. A bar closing with the index entering the oversold zone opens a window up; entering overbought opens a window down.
         */
        get: {
            parameters: {
                query: {
                    symbol: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RSISignal"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/candles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OHLCV history for a market, for the chart */
        get: {
            parameters: {
                query: {
                    symbol: string;
                    period_seconds: number;
                    from: number;
                    to: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Candle"][];
                    };
                };
                400: components["responses"]["Invalid"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/prizes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A wallet's published prizes and whether each was claimed */
        get: {
            parameters: {
                query: {
                    address: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            contract: string;
                            prizes: components["schemas"]["PrizeWinner"][];
                            /** @description The week index of each prize, in the same order. */
                            weeks: number[];
                        };
                    };
                };
                /** @description No prize pool configured. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The account's round trips in a market, newest first
         * @description What the chart marks — entries, exits and the open position. Routed by X-Account-Address like the rest of the account.
         */
        get: {
            parameters: {
                query: {
                    symbol: string;
                    /** @description Only this strategy's round trips; absent means all. */
                    strategy?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Trade"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What the crowd on-chain is doing with the market's asset — the card before an entry
         * @description Built from Nansen: the asset's day (price, move, buy and sell
         *     volume, net flow, liquidity), the biggest net buyers and sellers of
         *     the last day, the last hours of holder flows, and one sentence that
         *     says it. Refreshed lazily every few hours — the source meters
         *     credits — and served stale, flagged, when a refresh fails.
         */
        get: {
            parameters: {
                query: {
                    symbol: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MarketContext"];
                    };
                };
                400: components["responses"]["Invalid"];
                /** @description The source refused or failed and there is no card yet. */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Market context is not configured. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deposit/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What can be deposited from other chains, and what arrives
         * @description Any-chain deposits over Aurora Intents. Origin assets are on EVM
         *     chains only, because the wallet's own address is the refund address.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DepositOptions"];
                    };
                };
                /** @description Deposits are not configured. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deposit/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Quote a deposit into the requesting wallet and get a one-time deposit address
         * @description The recipient and the refund address are the wallet in
         *     X-Account-Address. Send `amount` of `origin_asset` (in its smallest
         *     unit) to `deposit_address` before `deadline`; Aurora swaps and
         *     delivers the destination asset to the wallet on Monad. A `dry`
         *     quote previews without reserving an address.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        origin_asset: string;
                        /** @description Smallest units of the origin asset. */
                        amount: string;
                        dry?: boolean;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DepositQuote"];
                    };
                };
                400: components["responses"]["Invalid"];
                /** @description Aurora refused, in its own words (a minimum amount, an unsupported pair). */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deposit/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Where a deposit stands */
        get: {
            parameters: {
                query: {
                    deposit_address: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DepositStatus"];
                    };
                };
                /** @description Aurora does not know this deposit, or failed. */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * This week's board for every strategy
         * @description One board per strategy, in lobby order: what the strategy made for everyone this week, how many played, how many hold a position right now, and the top wallets. Weeks start Monday 00:00 UTC.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Leaderboard"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/kill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Engage the kill switch — stops all opening, closing stays allowed */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        reason: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            killed?: true;
                            reason?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/revive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Release the kill switch */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            killed?: false;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Decimal number as a string, e.g. "20.5". Never a JSON number. */
        Decimal: string;
        /** @enum {string} */
        Side: "long" | "short";
        /** @enum {string} */
        OrderStatus: "unknown" | "pending" | "open" | "partially-filled" | "filled" | "canceled" | "expired" | "failed";
        Market: {
            /** @example MON */
            symbol: string;
            max_leverage: components["schemas"]["Decimal"];
            liquidation_leverage?: components["schemas"]["Decimal"];
            price_tick: components["schemas"]["Decimal"];
            size_step: components["schemas"]["Decimal"];
            /** @description How long an order may live on this venue. 0 means unlimited. */
            order_ttl_seconds: number;
            fees: components["schemas"]["Fees"];
        };
        /** @description Rates are fractions of notional ("0.00069" is 6.9 bps). */
        Fees: {
            maker_rate: components["schemas"]["Decimal"];
            taker_rate: components["schemas"]["Decimal"];
            builder_rate: components["schemas"]["Decimal"];
            /**
             * @description Whether the venue charges only the opening fill or every fill.
             * @enum {string}
             */
            charged_on: "open-only" | "every-fill";
            /** @description Flat charge per resting order, in collateral units. */
            posting_fee: components["schemas"]["Decimal"];
            /** @description Total fee fraction for open + close as taker. Use this, never taker_rate × 2. */
            round_trip_taker: components["schemas"]["Decimal"];
            round_trip_taker_bps: components["schemas"]["Decimal"];
            /** @description Price move fraction needed to cover the round trip. Independent of leverage. */
            break_even_move_taker: components["schemas"]["Decimal"];
        };
        Account: {
            /** @description Venue account id; "0" when the wallet has no exchange account yet. */
            id: string;
            balance: components["schemas"]["Decimal"];
            locked: components["schemas"]["Decimal"];
            /** @description False until the venue-side permission to trade through the API is granted. */
            can_trade: boolean;
            frozen: boolean;
            fee_tier: number;
            /**
             * @description Why can_trade is false. no_exchange_account — the wallet must fund and create its exchange account on-chain; forwarding_disabled — the account exists but has not allowed API order forwarding; frozen — the venue froze the account; active — ready to trade.
             * @enum {string}
             */
            status: "no_exchange_account" | "forwarding_disabled" | "frozen" | "active";
        };
        Candle: {
            /** @description Bar open time */
            t: number;
            o: components["schemas"]["Decimal"];
            h: components["schemas"]["Decimal"];
            l: components["schemas"]["Decimal"];
            c: components["schemas"]["Decimal"];
            v: components["schemas"]["Decimal"];
        };
        Leaderboard: {
            /** Format: date-time */
            week_start: string;
            /**
             * @description journal when the boards come from the platform's database; memory when from the process alone.
             * @enum {string}
             */
            source: "journal" | "memory";
            prize?: components["schemas"]["Prize"];
            boards: components["schemas"]["Board"][];
        };
        Trade: {
            strategy: string;
            symbol: string;
            side: components["schemas"]["Side"];
            size: components["schemas"]["Decimal"];
            entry_price: components["schemas"]["Decimal"];
            entry_fee: components["schemas"]["Decimal"];
            exit_price?: components["schemas"]["Decimal"];
            exit_fee?: components["schemas"]["Decimal"];
            pnl?: components["schemas"]["Decimal"];
            /**
             * @description Who closed the round trip; absent while open.
             * @enum {string}
             */
            close_reason?: "manual" | "horizon";
            /** Format: date-time */
            opened_at: string;
            /**
             * Format: date-time
             * @description Absent while the position is open.
             */
            closed_at?: string;
        };
        /** @description The on-chain weekly prize pool (StrategyPrizePool), when configured. */
        Prize: {
            contract: string;
            /** @description The collateral token the pool holds. */
            token: string;
            /** @description This week's index (Monday-aligned weeks since epoch). */
            week: number;
            pools: {
                strategy: string;
                pool: components["schemas"]["Decimal"];
            }[];
            last_week: number;
            /** @description Last week's published winners, best first per strategy. */
            winners: components["schemas"]["PrizeWinner"][];
        };
        PrizeWinner: {
            strategy: string;
            wallet: string;
            amount: components["schemas"]["Decimal"];
            pnl: components["schemas"]["Decimal"];
            claimed: boolean;
        };
        Board: {
            /** @example ma-cross */
            id: string;
            name: string;
            /** @description What the strategy is */
            tagline: string;
            /** @description How often it asks for a decision. */
            rhythm: string;
            /** @description What the strategy made for all its players this week, fees included. */
            pnl: components["schemas"]["Decimal"];
            players: number;
            trades: number;
            /** @description Wallets holding a position under this strategy. */
            active_now: number;
            top: {
                wallet: string;
                pnl: components["schemas"]["Decimal"];
                trades: number;
            }[];
        };
        RSISignal: {
            symbol: string;
            period_seconds: number;
            length: number;
            oversold: components["schemas"]["Decimal"];
            overbought: components["schemas"]["Decimal"];
            ready: boolean;
            /** @description The index as of the last closed bar, 0..100. */
            value: components["schemas"]["Decimal"];
            forming: boolean;
            window?: {
                side: components["schemas"]["Side"];
                /** Format: date-time */
                opened_at: string;
                /** Format: date-time */
                expires_at: string;
            };
            last_cross?: {
                side: components["schemas"]["Side"];
                /** Format: date-time */
                at: string;
                value: components["schemas"]["Decimal"];
            };
            points: {
                /** Format: date-time */
                at: string;
                close: components["schemas"]["Decimal"];
                value?: components["schemas"]["Decimal"];
            }[];
        };
        MACrossSignal: {
            symbol: string;
            period_seconds: number;
            /** @description Fast average length */
            fast: number;
            /** @description Slow average length */
            slow: number;
            /** @description False until slow closed bars exist. */
            ready: boolean;
            /**
             * @description Which average is on top as of the last closed bar.
             * @enum {string}
             */
            trend: "up" | "down" | "flat";
            /** @description Whether the last point is the bar still forming. */
            forming: boolean;
            /** @description Present while an entry is offered after a cross. */
            window?: {
                side: components["schemas"]["Side"];
                /** Format: date-time */
                opened_at: string;
                /** Format: date-time */
                expires_at: string;
            };
            last_cross?: {
                side: components["schemas"]["Side"];
                /** Format: date-time */
                at: string;
            };
            points: {
                /** Format: date-time */
                at: string;
                open: components["schemas"]["Decimal"];
                high: components["schemas"]["Decimal"];
                low: components["schemas"]["Decimal"];
                close: components["schemas"]["Decimal"];
                fast?: components["schemas"]["Decimal"];
                slow?: components["schemas"]["Decimal"];
            }[];
        };
        /** @description The most recent round trip's outcome, so the screen can say a position was closed while the user was away. */
        LastClose: {
            symbol: string;
            side: components["schemas"]["Side"];
            /** @enum {string} */
            reason: "manual" | "horizon";
            price: components["schemas"]["Decimal"];
            pnl: components["schemas"]["Decimal"];
            /** Format: date-time */
            at: string;
        };
        Position: {
            id: string;
            symbol: string;
            side: components["schemas"]["Side"];
            size: components["schemas"]["Decimal"];
            entry_price: components["schemas"]["Decimal"];
            notional: components["schemas"]["Decimal"];
            collateral: components["schemas"]["Decimal"];
            leverage: components["schemas"]["Decimal"];
            unrealized_pnl: components["schemas"]["Decimal"];
            fees_paid: components["schemas"]["Decimal"];
            /** Format: date-time */
            opened_at?: string;
            /**
             * Format: date-time
             * @description When the horizon closes this position; absent without one.
             */
            closes_at?: string;
        };
        Limits: {
            allowed_symbols: string[];
            min_notional: components["schemas"]["Decimal"];
            max_notional: components["schemas"]["Decimal"];
            max_leverage: components["schemas"]["Decimal"];
            max_total_exposure: components["schemas"]["Decimal"];
            max_open_positions: number;
            daily_loss: components["schemas"]["Decimal"];
            cooldown_seconds: number;
        };
        /** @description How much of the limits is currently used. */
        Risk: {
            open_positions: number;
            exposure: components["schemas"]["Decimal"];
            daily_loss: components["schemas"]["Decimal"];
            /** Format: date-time */
            last_open?: string;
        };
        State: {
            last_close?: components["schemas"]["LastClose"];
            /** @example perpl */
            venue: string;
            account: components["schemas"]["Account"];
            positions: components["schemas"]["Position"][];
            limits: components["schemas"]["Limits"];
            risk: components["schemas"]["Risk"];
            killed: boolean;
            kill_note?: string;
        };
        OpenRequest: {
            /** @example MON */
            symbol: string;
            side: components["schemas"]["Side"];
            /** @description Position value in collateral units. */
            notional: components["schemas"]["Decimal"];
            /** @description Defaults to 1. */
            leverage?: components["schemas"]["Decimal"];
            /** @description Which strategy this entry belongs to, for the leaderboard: direction (default), ma-cross or rsi. */
            strategy?: string;
            /** @description The strategy's exit: the platform closes the position this many seconds after it opens (10 s to 24 h). 0 or absent leaves the close to the user. A manual close disarms it. */
            horizon_seconds?: number;
        };
        CloseRequest: {
            symbol: string;
            /** @description Which strategy's key closes; defaults to the X-Strategy header. */
            strategy?: string;
        };
        Order: {
            /** @description The idempotency key the service generated. */
            client_id: string;
            venue_id: string;
            symbol: string;
            side: components["schemas"]["Side"];
            status: components["schemas"]["OrderStatus"];
            size: components["schemas"]["Decimal"];
            filled_size: components["schemas"]["Decimal"];
            avg_price: components["schemas"]["Decimal"];
            /** @description Gross fee charged, protocol plus builder. */
            fee: components["schemas"]["Decimal"];
            builder_fee: components["schemas"]["Decimal"];
            rejection?: {
                code?: string;
                detail?: string;
            } | null;
            /** Format: date-time */
            updated_at?: string;
        };
        ExchangeNetwork: {
            /** @enum {string} */
            network: "testnet" | "mainnet";
            /** Format: int64 */
            chain_id: number;
            /** Format: uri */
            rpc_url: string;
            /** Format: uri */
            explorer: string;
            /** @description Exchange contract */
            exchange_address: string;
            /** @description ERC-20 collateral token */
            collateral_token: string;
            collateral_symbol: string;
            collateral_decimals: number;
            min_account_open_amount: components["schemas"]["Decimal"];
            /** @description The same minimum as the raw on-chain integer to pass to createAccount. */
            min_account_open_raw: string;
        };
        EnrollPayload: {
            /** @description Single-use; identifies the pending key. */
            handle: string;
            /** @description The strategy the key is for; absent for a wallet-wide key. */
            strategy?: string;
            /** @description The key being enrolled */
            public_key: string;
            /** @description Sign-In-With-Ethereum text; sign as a personal message. */
            sign_in_message: string;
            /** @description EIP-712 document (types, primaryType, domain, message). Sign it exactly as given. */
            typed_data: Record<string, never>;
            /** @description The prose the user reads in the wallet prompt. */
            statement: string;
            builder_id: number;
            /** @description 1 = 0.1 bps; the ceiling the user consents to. */
            max_builder_fee_per_100k: number;
            /** Format: date-time */
            expires_at: string;
        };
        EnrolledKey: {
            address: string;
            /** @description The strategy this key trades for; empty for a wallet-wide key. */
            strategy: string;
            /** @description True when the device derived the key from the passkey. */
            derived: boolean;
            label: string;
            builder_id: number;
            max_builder_fee_per_100k: number;
            /** @example 0.050% */
            max_builder_fee_pct?: string;
            /** Format: date-time */
            enrolled_at: string;
        };
        MarketContext: {
            symbol: string;
            chain: string;
            token_address: string;
            token_symbol: string;
            price_usd: components["schemas"]["Decimal"];
            change_24h_pct: components["schemas"]["Decimal"];
            volume_24h_usd: components["schemas"]["Decimal"];
            buy_volume_usd: components["schemas"]["Decimal"];
            sell_volume_usd: components["schemas"]["Decimal"];
            netflow_usd: components["schemas"]["Decimal"];
            liquidity_usd: components["schemas"]["Decimal"];
            market_cap_usd: components["schemas"]["Decimal"];
            /** @enum {string} */
            lean: "buyers" | "sellers" | "balanced";
            headline: string;
            hours: {
                /** Format: date-time */
                at: string;
                inflow_usd: components["schemas"]["Decimal"];
                outflow_usd: components["schemas"]["Decimal"];
                complete: boolean;
            }[];
            top_buyers: components["schemas"]["ContextTrader"][];
            top_sellers: components["schemas"]["ContextTrader"][];
            /** @example nansen */
            source: string;
            /** Format: date-time */
            updated_at: string;
            stale: boolean;
        };
        ContextTrader: {
            address: string;
            label?: string;
            bought_usd: components["schemas"]["Decimal"];
            sold_usd: components["schemas"]["Decimal"];
        };
        DepositOptions: {
            destination: {
                asset_id: string;
                chain: string;
                symbol: string;
                decimals: number;
            };
            options: {
                asset_id: string;
                chain: string;
                chain_name: string;
                symbol: string;
                decimals: number;
                price_usd: components["schemas"]["Decimal"];
            }[];
        };
        DepositQuote: {
            /** @description Absent on a dry quote. */
            deposit_address?: string;
            origin_asset: string;
            amount_in: components["schemas"]["Decimal"];
            amount_in_usd: components["schemas"]["Decimal"];
            amount_out: components["schemas"]["Decimal"];
            amount_out_usd: components["schemas"]["Decimal"];
            /** @description Smallest units of the destination asset. */
            min_amount_out: string;
            time_estimate_seconds: number;
            /** Format: date-time */
            deadline: string;
            dry: boolean;
        };
        DepositStatus: {
            /** @enum {string} */
            status: "PENDING_DEPOSIT" | "KNOWN_DEPOSIT_TX" | "INCOMPLETE_DEPOSIT" | "PROCESSING" | "SUCCESS" | "REFUNDED" | "FAILED";
            /** Format: date-time */
            updated_at: string;
            amount_in?: string;
            amount_out?: string;
            tx_hashes: string[];
        };
        Error: {
            /**
             * @description Stable machine code. Policy denials use the engine's reasons:
             *     kill_switch, symbol_not_allowed, notional_too_large, notional_too_small,
             *     leverage_too_high, daily_loss_limit_reached, cooldown,
             *     too_many_open_positions, total_exposure_too_large, malformed_request.
             *     Others: invalid_request, venue_rejected, venue_disconnected (503: outcome
             *     unknown), enrollment_unavailable, no_key, no_exchange_account (409: fund and
             *     activate the wallet's exchange account), forwarding_disabled (409),
             *     venue_unconfirmed (504: acknowledged, outcome unknown — reconcile then retry),
             *     unknown, re-read state and retry), unknown_market, no_position,
             *     no_credentials, unauthenticated (401: the wallet registered a
             *     request-signing key and this request is not signed by it),
             *     context_unavailable and deposit_unavailable (503: not configured),
             *     partner_error (502: Nansen or Aurora refused, message is theirs), internal.
             */
            error: string;
            /** @description For a person. */
            message: string;
            limit?: components["schemas"]["Decimal"];
            actual?: components["schemas"]["Decimal"];
            /** @description Set when the refusal is temporary, e.g. a cooldown. */
            retry_after_seconds?: number;
        };
    };
    responses: {
        /** @description Malformed request */
        Invalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Refused by the policy engine */
        Denied: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unknown market or no open position */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The venue refused the order */
        VenueRejected: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
