/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            status?: "ok";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/markets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tradable markets with the fee schedule that applies to this account */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Market"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Account balance, open positions, limits in force and how much of them is used */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["State"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open a position
         * @description Sized by notional in collateral units; the service derives the size
         *     from the venue's mark price. Returns once the venue accepted or refused
         *     the order — fills may still be in flight for a resting order, but a
         *     market order is filled on return.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OpenRequest"];
                };
            };
            responses: {
                /** @description Accepted by the venue. Check `status`: a venue-side failure arrives here with status `failed` and a `rejection`. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Order"];
                    };
                };
                400: components["responses"]["Invalid"];
                403: components["responses"]["Denied"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["VenueRejected"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close the open position in a market
         * @description The service sizes the close from the venue's own position, never from
         *     the caller. Closing is never refused by the policy engine.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CloseRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Order"];
                    };
                };
                400: components["responses"]["Invalid"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["VenueRejected"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exchange/enroll/payload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start enrolling an exchange API key for a wallet
         * @description The platform generates an Ed25519 key pair and asks the venue for two
         *     things: the wallet's sign-in message, and the EIP-712 document that
         *     binds the new key to the wallet and to our builder terms. The wallet
         *     signs both — `sign_in_message` as a personal message (EIP-191),
         *     `typed_data` as EIP-712. `statement` is the prose the user reads. The
         *     private key waits on the server until `expires_at`.
         *
         *     The sign-in is what creates the wallet's profile at the venue on first
         *     contact; without it the venue refuses to enroll a key.
         *
         *     When signing with viem, pass `domain.chainId` as a **bigint**: given a
         *     string, viem drops chainId from the domain type and the venue rejects
         *     the signature.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description The wallet the key is for */
                        address: string;
                        /** @description Shown on the venue's key page. */
                        label?: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnrollPayload"];
                    };
                };
                400: components["responses"]["Invalid"];
                422: components["responses"]["VenueRejected"];
                /** @description No builder code configured; enrollment is unavailable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exchange/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finish enrolling with the wallet's signature
         * @description The platform signs the wallet in at the venue with `sign_in_signature`
         *     (creating its profile on first contact), then computes the EIP-712
         *     digest, signs it with the pending Ed25519 key as proof of possession,
         *     and submits it with `signature`. On success the key is stored and the
         *     platform can trade for this wallet. A handle is single-use.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        handle: string;
                        /** @description The wallet's EIP-191 signature over sign_in_message */
                        sign_in_signature: string;
                        /** @description The wallet's EIP-712 signature over typed_data */
                        signature: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnrolledKey"];
                    };
                };
                400: components["responses"]["Invalid"];
                422: components["responses"]["VenueRejected"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exchange/key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The enrolled key for a wallet, without secrets */
        get: {
            parameters: {
                query: {
                    address: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnrolledKey"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/kill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Engage the kill switch — stops all opening, closing stays allowed */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        reason: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            killed?: true;
                            reason?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/revive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Release the kill switch */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            killed?: false;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Decimal number as a string, e.g. "20.5". Never a JSON number. */
        Decimal: string;
        /** @enum {string} */
        Side: "long" | "short";
        /** @enum {string} */
        OrderStatus: "unknown" | "pending" | "open" | "partially-filled" | "filled" | "canceled" | "expired" | "failed";
        Market: {
            /** @example MON */
            symbol: string;
            max_leverage: components["schemas"]["Decimal"];
            liquidation_leverage?: components["schemas"]["Decimal"];
            price_tick: components["schemas"]["Decimal"];
            size_step: components["schemas"]["Decimal"];
            /** @description How long an order may live on this venue. 0 means unlimited. */
            order_ttl_seconds: number;
            fees: components["schemas"]["Fees"];
        };
        /** @description Rates are fractions of notional ("0.00069" is 6.9 bps). */
        Fees: {
            maker_rate: components["schemas"]["Decimal"];
            taker_rate: components["schemas"]["Decimal"];
            builder_rate: components["schemas"]["Decimal"];
            /**
             * @description Whether the venue charges only the opening fill or every fill.
             * @enum {string}
             */
            charged_on: "open-only" | "every-fill";
            /** @description Flat charge per resting order, in collateral units. */
            posting_fee: components["schemas"]["Decimal"];
            /** @description Total fee fraction for open + close as taker. Use this, never taker_rate × 2. */
            round_trip_taker: components["schemas"]["Decimal"];
            round_trip_taker_bps: components["schemas"]["Decimal"];
            /** @description Price move fraction needed to cover the round trip. Independent of leverage. */
            break_even_move_taker: components["schemas"]["Decimal"];
        };
        Account: {
            id: string;
            balance: components["schemas"]["Decimal"];
            locked: components["schemas"]["Decimal"];
            /** @description False until the venue-side permission to trade through the API is granted. */
            can_trade: boolean;
            frozen: boolean;
            fee_tier: number;
        };
        Position: {
            id: string;
            symbol: string;
            side: components["schemas"]["Side"];
            size: components["schemas"]["Decimal"];
            entry_price: components["schemas"]["Decimal"];
            notional: components["schemas"]["Decimal"];
            collateral: components["schemas"]["Decimal"];
            leverage: components["schemas"]["Decimal"];
            unrealized_pnl: components["schemas"]["Decimal"];
            fees_paid: components["schemas"]["Decimal"];
            /** Format: date-time */
            opened_at?: string;
        };
        Limits: {
            allowed_symbols: string[];
            min_notional: components["schemas"]["Decimal"];
            max_notional: components["schemas"]["Decimal"];
            max_leverage: components["schemas"]["Decimal"];
            max_total_exposure: components["schemas"]["Decimal"];
            max_open_positions: number;
            daily_loss: components["schemas"]["Decimal"];
            cooldown_seconds: number;
        };
        /** @description How much of the limits is currently used. */
        Risk: {
            open_positions: number;
            exposure: components["schemas"]["Decimal"];
            daily_loss: components["schemas"]["Decimal"];
            /** Format: date-time */
            last_open?: string;
        };
        State: {
            /** @example perpl */
            venue: string;
            account: components["schemas"]["Account"];
            positions: components["schemas"]["Position"][];
            limits: components["schemas"]["Limits"];
            risk: components["schemas"]["Risk"];
            killed: boolean;
            kill_note?: string;
        };
        OpenRequest: {
            /** @example MON */
            symbol: string;
            side: components["schemas"]["Side"];
            /** @description Position value in collateral units. */
            notional: components["schemas"]["Decimal"];
            /** @description Defaults to 1. */
            leverage?: components["schemas"]["Decimal"];
        };
        CloseRequest: {
            symbol: string;
        };
        Order: {
            /** @description The idempotency key the service generated. */
            client_id: string;
            venue_id: string;
            symbol: string;
            side: components["schemas"]["Side"];
            status: components["schemas"]["OrderStatus"];
            size: components["schemas"]["Decimal"];
            filled_size: components["schemas"]["Decimal"];
            avg_price: components["schemas"]["Decimal"];
            /** @description Gross fee charged, protocol plus builder. */
            fee: components["schemas"]["Decimal"];
            builder_fee: components["schemas"]["Decimal"];
            rejection?: {
                code?: string;
                detail?: string;
            } | null;
            /** Format: date-time */
            updated_at?: string;
        };
        EnrollPayload: {
            /** @description Single-use; identifies the pending key. */
            handle: string;
            /** @description Sign-In-With-Ethereum text; sign as a personal message. */
            sign_in_message: string;
            /** @description EIP-712 document (types, primaryType, domain, message). Sign it exactly as given. */
            typed_data: Record<string, never>;
            /** @description The prose the user reads in the wallet prompt. */
            statement: string;
            builder_id: number;
            /** @description 1 = 0.1 bps; the ceiling the user consents to. */
            max_builder_fee_per_100k: number;
            /** Format: date-time */
            expires_at: string;
        };
        EnrolledKey: {
            address: string;
            label: string;
            builder_id: number;
            max_builder_fee_per_100k: number;
            /** @example 0.050% */
            max_builder_fee_pct?: string;
            /** Format: date-time */
            enrolled_at: string;
        };
        Error: {
            /**
             * @description Stable machine code. Policy denials use the engine's reasons:
             *     kill_switch, symbol_not_allowed, notional_too_large, notional_too_small,
             *     leverage_too_high, daily_loss_limit_reached, cooldown,
             *     too_many_open_positions, total_exposure_too_large, malformed_request.
             *     Others: invalid_request, venue_rejected, venue_disconnected (503: outcome
             *     unknown), enrollment_unavailable, no_key,
             *     unknown, re-read state and retry), unknown_market, no_position,
             *     no_credentials, internal.
             */
            error: string;
            /** @description For a person. */
            message: string;
            limit?: components["schemas"]["Decimal"];
            actual?: components["schemas"]["Decimal"];
            /** @description Set when the refusal is temporary, e.g. a cooldown. */
            retry_after_seconds?: number;
        };
    };
    responses: {
        /** @description Malformed request */
        Invalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Refused by the policy engine */
        Denied: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unknown market or no open position */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The venue refused the order */
        VenueRejected: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
